const app = document.querySelector('#app');
const data = {
  classes: [{id:'a',name:'2º ano A',teacher:'Mariana Costa'},{id:'b',name:'3º ano B',teacher:'João Pereira'}],
  groups: [
    {id:'azul',name:'Grupo Azul',color:'#5ba7dd',classId:'a',students:['Ana Clara Souza','Bernardo Lima','Cecília Martins']},
    {id:'amarelo',name:'Grupo Amarelo',color:'#efbd3e',classId:'a',students:['Davi Oliveira','Elisa Rocha']},
    {id:'verde',name:'Grupo Verde',color:'#61b986',classId:'b',students:['Felipe Alves','Gabriela Nunes']},
    {id:'vermelho',name:'Grupo Vermelho',color:'#e57c74',classId:'b',students:['Heitor Santos','Isabela Moraes']}
  ],
  reports: [
    {id:1,month:'Agosto de 2026',sent:'31/08/2026',group:'azul',focus:'Autorregulação emocional',answers:{'Autoconhecimento e autocuidado':'Frequentemente','Autorregulação emocional':'Às vezes','Empatia e cooperação':'Frequentemente','Convivência e respeito':'Frequentemente','Autonomia e participação':'Às vezes'},note:'O grupo reconhece emoções, mas ainda precisa de estratégias para lidar com frustrações.',observations:{'Ana Clara Souza':'Nomeou as emoções durante a roda de conversa.','Bernardo Lima':'Utilizou a respiração guiada com apoio.'}},
    {id:2,month:'Julho de 2026',sent:'30/07/2026',group:'amarelo',focus:'Empatia e cooperação',answers:{'Autoconhecimento e autocuidado':'Frequentemente','Autorregulação emocional':'Frequentemente','Empatia e cooperação':'Raramente','Convivência e respeito':'Às vezes','Autonomia e participação':'Frequentemente'},note:'Nas propostas em dupla, o grupo ainda necessita de mediação para escutar diferentes ideias.',observations:{'Davi Oliveira':'Demonstrou interesse em ajudar os colegas após orientação.','Elisa Rocha':'Compartilhou materiais de forma espontânea.'}},
    {id:3,month:'Junho de 2026',sent:'28/06/2026',group:'verde',focus:'Convivência e respeito',answers:{'Autoconhecimento e autocuidado':'Às vezes','Autorregulação emocional':'Frequentemente','Empatia e cooperação':'Às vezes','Convivência e respeito':'Raramente','Autonomia e participação':'Frequentemente'},note:'Os combinados precisam ser retomados em situações de brincadeira coletiva.',observations:{'Felipe Alves':'Aceitou retomar o diálogo após conflito no jogo.','Gabriela Nunes':'Apoiou a organização dos materiais.'}},
    {id:4,month:'Agosto de 2026',sent:'31/08/2026',group:'vermelho',focus:'Autonomia e participação',answers:{'Autoconhecimento e autocuidado':'Frequentemente','Autorregulação emocional':'Frequentemente','Empatia e cooperação':'Frequentemente','Convivência e respeito':'Frequentemente','Autonomia e participação':'Às vezes'},note:'O grupo participa com entusiasmo e pode ampliar a iniciativa nas escolhas de tarefas.',observations:{'Heitor Santos':'Precisou de convite para compartilhar sua ideia.','Isabela Moraes':'Assumiu a função de organizar os livros.'}}
  ],
  freeNotes:{'Ana Clara Souza':[{date:'05/09/2026',frequency:'semanal',text:'Participou com segurança da leitura mediada.'}],'Bernardo Lima':[{date:'03/09/2026',frequency:'pontual',text:'Pediu uma pausa e retornou à atividade após a respiração guiada.'}]}
};
const state={role:'',page:'inicio',group:'azul',student:'Ana Clara Souza',report:1,editing:false,classId:''};
const areas=['Autoconhecimento e autocuidado','Autorregulação emocional','Empatia e cooperação','Convivência e respeito','Autonomia e participação'];
const low=new Set(['Ainda não observado','Raramente','Às vezes']);
const catalog={
  'Autoconhecimento e autocuidado':['Competência Geral 8','Reconhecer emoções e práticas de cuidado consigo.','Termômetro das emoções com cartões de situações.','O Monstro das Cores','O que meu corpo me conta quando sinto uma emoção forte?','Diário coletivo das emoções.'],
  'Autorregulação emocional':['Competência Geral 8','Experimentar estratégias de pausa e calma diante de frustrações.','Respiração dos cinco dedos e organização do cantinho da calma.','Quando me sinto bravo','O que podemos fazer antes de reagir quando algo não sai como esperamos?','Caixa de estratégias de calma.'],
  'Empatia e cooperação':['Competência Geral 9','Escutar o outro e cooperar em objetivos compartilhados.','Missão em duplas com papéis alternados.','O ponto','Como posso ajudar um colega a participar?','Mural de atitudes cooperativas.'],
  'Convivência e respeito':['Competência Geral 9','Resolver conflitos com diálogo e valorizar os combinados da turma.','Dramatização de conflitos cotidianos e combinados.','O grande rabanete','Como resolvemos um conflito sem machucar ninguém?','Cartaz vivo dos combinados.'],
  'Autonomia e participação':['Competência Geral 10','Ampliar iniciativa, responsabilidade e expressão de ideias.','Responsabilidades rotativas e escolha de estratégias para a tarefa.','Extraordinário','Qual ideia sua pode melhorar nossa turma?','Conselho de crianças para organizar uma ação da turma.']
};
const esc=v=>String(v||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const getGroup=id=>data.groups.find(g=>g.id===id); const getClass=id=>data.classes.find(c=>c.id===id); const groupReports=id=>data.reports.filter(r=>r.group===id); const latest=id=>groupReports(id).slice().sort((a,b)=>b.id-a.id)[0];
const notice=()=>'<div class="notice">🔒 <b>Informações pedagógicas confidenciais.</b> Registre situações observadas, avanços e estratégias de apoio; evite rótulos permanentes.</div>';
const header=t=>`<header class="topbar"><div><p class="eyebrow">${esc(state.role)}</p><h1>${t}</h1></div><div class="user"><div class="avatar">${state.role==='Direção escolar'?'D':'M'}</div><small>${state.role==='Direção escolar'?'Equipe gestora':'Professora Mariana'}</small></div></header>`;

function nav(){const items=state.role==='Direção escolar'?[['inicio','Início'],['turmas','Turmas'],['acompanhamento','Acompanhamento das turmas']]:[['inicio','Início'],['grupos','Grupos'],['alunos','Alunos'],['formularios','Formulários'],['planejamentos','Planejamentos']];return `<aside class="side"><div class="brand"><span class="brand-mark">✦</span> Trilhas</div><nav class="nav">${items.map(([id,label])=>`<button data-page="${id}" class="${state.page===id?'active':''}">${label}</button>`).join('')}</nav><div class="side-bottom">Demonstração pedagógica<button class="logout" data-action="logout">Trocar perfil</button></div></aside>`}
function planning(id,full=false){const group=getGroup(id), reports=groupReports(id), counts=Object.fromEntries(areas.map(a=>[a,0]));reports.forEach(r=>areas.forEach(a=>{if(low.has(r.answers[a]))counts[a]++}));const priority=areas.slice().sort((a,b)=>counts[b]-counts[a])[0], item=catalog[priority], report=latest(id);return `<article class="recommendation" style="border-left-color:${group.color}"><h3>${group.name} · ${priority}</h3><p><b>Base do acompanhamento:</b> ${reports.length} relatório(s); foco recente: ${report.focus}.</p><p><b>BNCC:</b> ${item[0]} · <b>Objetivo:</b> ${item[1]}</p><p><b>Atividade principal:</b> ${item[2]}</p>${full?`<p><b>Dinâmica:</b> grupos pequenos com papéis rotativos e momento de escuta.</p><p><b>Literatura:</b> ${item[3]}.</p><p><b>Roda de conversa:</b> “${item[4]}”</p><p><b>Projeto:</b> ${item[5]}</p><p><b>Acompanhamento:</b> retomar este indicador no próximo relatório e registrar evidências observáveis.</p>`:''}<button class="action" data-action="open-plan" data-id="${group.id}">${full?'Ver todos os planejamentos':'Ver planejamento completo →'}</button></article>`}
function teacherHome(){return `${header('Visão geral')}${notice()}<div class="cards"><div class="metric"><span class="icon">👧</span><b>9</b><span>Alunos acompanhados</span></div><div class="metric"><span class="icon">🎨</span><b>4</b><span>Grupos</span></div><div class="metric"><span class="icon">📝</span><b>${data.reports.length}</b><span>Relatórios no histórico</span></div><div class="metric"><span class="icon">📅</span><b>Set.</b><span>Próximo ciclo</span></div></div><h2 style="margin-top:24px">Planejamento mensal por grupo</h2><p class="muted">Cada sugestão considera as respostas e o histórico do respectivo grupo.</p>${data.groups.map(g=>`<section class="panel" style="margin:12px 0;border-left:8px solid ${g.color}">${planning(g.id)}</section>`).join('')}`}
function groupsView(editing=null){const group=editing?getGroup(editing):null;const classStudents=group?data.groups.filter(g=>g.classId===group.classId).flatMap(g=>g.students):[];const all=[...new Set(classStudents)];return `${header(editing?`Editar integrantes · ${group.name}`:'Grupos')}${notice()}${editing?`<section class="panel"><h2>${group.name} · ${getClass(group.classId).name}</h2><p class="muted">Os relatórios já realizados permanecem guardados no histórico mesmo após mudanças.</p>${all.map(s=>`<label class="row"><span><input type="checkbox" name="member" value="${esc(s)}" ${group.students.includes(s)?'checked':''}> ${esc(s)}</span></label>`).join('')}<div class="form-actions"><button class="secondary" data-page="grupos">Cancelar</button><button class="save" data-action="save-members" data-id="${group.id}">Salvar integrantes</button></div></section>`:`<div class="rows">${data.groups.map(g=>`<section class="panel group-row" style="border-left:9px solid ${g.color}"><div><h2>${g.name}</h2><p class="muted">${getClass(g.classId).name} · ${g.students.length} integrantes</p><p>${g.students.map(esc).join(' · ')}</p></div><div class="form-actions"><button class="secondary" data-action="answer" data-id="${g.id}">Responder formulário</button><button class="action" data-action="edit-members" data-id="${g.id}">Editar integrantes</button></div></section>`).join('')}</div>`}`}
function reportForm(id,existing=null){const group=getGroup(id), report=existing||{answers:Object.fromEntries(areas.map(a=>[a,'Às vezes'])),note:'',observations:{}}, options=['Ainda não observado','Raramente','Às vezes','Frequentemente','Sempre'];return `${header(`${existing?'Editar relatório':'Relatório mensal'} · ${group.name}`)}${notice()}<form class="form" id="report-form" data-group="${group.id}" data-report="${existing?existing.id:''}"><div class="report-info"><div><span>Período registrado automaticamente</span><b>01 a 30 de setembro de 2026</b></div><div><span>Turma</span><b>${getClass(group.classId).name}</b></div></div><div class="form-grid">${areas.map(a=>`<div class="field"><label>${a}</label><select name="${a}">${options.map(o=>`<option ${report.answers[a]===o?'selected':''}>${o}</option>`).join('')}</select></div>`).join('')}<div class="field full"><label>Observação geral do grupo</label><textarea name="note" placeholder="Descreva o contexto e as estratégias utilizadas.">${esc(report.note)}</textarea></div></div><h2>Observações individuais</h2><p class="muted">Campos opcionais para cada estudante do grupo.</p><div class="form-grid">${group.students.map(s=>`<div class="field"><label>${esc(s)}</label><textarea name="student-${esc(s)}" placeholder="Observação individual opcional">${esc(report.observations[s]||'')}</textarea></div>`).join('')}</div><div class="form-actions"><button type="button" class="secondary" data-page="formularios">Salvar rascunho</button><button class="save">${existing?'Salvar alterações':'Enviar relatório'}</button></div></form>`}
function reportsView(){return `${header('Formulários respondidos')}${notice()}<section class="panel"><h2>Histórico mensal</h2>${data.reports.slice().sort((a,b)=>b.id-a.id).map(r=>{const g=getGroup(r.group),edit=latest(r.group).id===r.id;return `<div class="row"><div><b>${r.month} · ${g.name}</b><br><small>${getClass(g.classId).name} · ${getClass(g.classId).teacher} · enviado em ${r.sent}</small><br><span class="tag yellow">Atenção: ${r.focus}</span></div><div><button class="action" data-action="view-report" data-id="${r.id}">Ver formulário</button>${edit?` · <button class="action" data-action="edit-report" data-id="${r.id}">Editar</button>`:''}</div></div>`}).join('')}</section>`}
function reportDetail(id){const r=data.reports.find(x=>x.id===Number(id)),g=getGroup(r.group),edit=latest(r.group).id===r.id;return `${header(`${r.month} · ${g.name}`)}${notice()}<section class="panel"><h2>Formulário respondido</h2>${areas.map(a=>`<div class="row"><span>${a}</span><span class="tag ${low.has(r.answers[a])?'yellow':''}">${r.answers[a]}</span></div>`).join('')}<h3 style="margin-top:20px">Observação do grupo</h3><p>${esc(r.note)}</p><h3>Observações individuais</h3>${g.students.map(s=>`<p><b>${esc(s)}:</b> ${esc(r.observations[s]||'Sem observação neste relatório.')}</p>`).join('')}<h3>Planejamento recomendado</h3>${planning(g.id,true)}${edit?`<button class="secondary" data-action="edit-report" data-id="${r.id}">Editar relatório mais recente</button>`:''}</section>`}
function studentsView(){const students=data.groups.flatMap(g=>g.students.map(name=>({name,g})));return `${header('Alunos')}${notice()}<section class="panel"><h2>Alunos das suas turmas</h2>${students.map(({name,g})=>`<div class="row"><div class="student"><div class="avatar">${esc(name[0])}</div><div><b>${esc(name)}</b><br><small>${getClass(g.classId).name} · ${g.name} · último relatório: ${latest(g.id).month}</small></div></div><button class="action" data-action="history" data-id="${esc(name)}">Histórico</button></div>`).join('')}</section>`}
function studentHistory(name){const group=data.groups.find(g=>g.students.includes(name)),reports=groupReports(group.id),notes=data.freeNotes[name]||[],entries=[...reports.map(r=>({date:r.sent,title:`${r.month} · ${group.name}`,text:`${r.focus}: ${r.observations[name]||r.note}`})),...notes.map(n=>({date:n.date,title:`Observação ${n.frequency}`,text:n.text}))];return `${header(`Histórico · ${name}`)}${notice()}<section class="panel"><div class="section-title"><div><h2>${esc(name)}</h2><p class="muted">${getClass(group.classId).name} · ${group.name}</p></div><button class="secondary" data-action="generate-student" data-id="${esc(name)}">Gerar relatório do aluno</button></div>${entries.map(e=>`<div class="row"><div><b>${e.title}</b><br><small>${e.date}</small><p>${esc(e.text)}</p></div></div>`).join('')}<form id="free-note" data-student="${esc(name)}" class="form" style="margin-top:18px"><h3>Nova observação</h3><div class="form-grid"><div class="field"><label>Data</label><input name="date" type="date" value="2026-09-07"></div><div class="field"><label>Frequência</label><select name="frequency"><option>diária</option><option>semanal</option><option>pontual</option><option>outra</option></select></div><div class="field full"><label>Observação contextualizada</label><textarea name="text" required placeholder="Registre uma situação, avanço ou estratégia de apoio."></textarea></div></div><button class="save">Adicionar à linha do tempo</button></form></section>`}
function studentReport(name){const group=data.groups.find(g=>g.students.includes(name)),reports=groupReports(group.id),notes=data.freeNotes[name]||[],focus=reports.map(r=>r.focus).join(', '),text=`RELATÓRIO PEDAGÓGICO\n\nAluno(a): ${name}\nTurma: ${getClass(group.classId).name}\nPeríodo analisado: junho a setembro de 2026\n\nSíntese: Nos relatórios do ${group.name}, foram acompanhados os campos de ${focus}. O estudante apresenta avanços quando participa das propostas mediadas e se beneficia de estratégias de apoio contextualizadas.\n\nObservações registradas: ${[...reports.map(r=>r.observations[name]).filter(Boolean),...notes.map(n=>n.text)].join(' ')}\n\nNecessidades de acompanhamento: manter oportunidades de participação, escuta e prática das estratégias sugeridas ao grupo.\n\nSugestão pedagógica: retomar, no próximo ciclo, atividades relacionadas a ${latest(group.id).focus} e registrar evidências observáveis de progresso.`;return `${header('Relatório do aluno')}${notice()}<section class="panel"><h2>${esc(name)}</h2><textarea id="student-report-text" style="width:100%;min-height:310px">${esc(text)}</textarea><div class="form-actions"><button class="secondary" data-action="history" data-id="${esc(name)}">Voltar ao histórico</button><button class="save" data-action="copy-report">Copiar relatório</button></div></section>`}
function plansView(){return `${header('Planejamentos')}${notice()}${data.groups.map(g=>`<section class="panel" style="margin-bottom:14px">${planning(g.id,true)}</section>`).join('')}`}
function directionView(){if(state.page==='turmas')return `${header('Turmas')}${notice()}<section class="panel"><div class="section-title"><h2>Turmas e professores regentes</h2><button class="secondary" data-action="new-class">+ Criar turma</button></div>${data.classes.map(c=>`<div class="row"><div><b>${c.name}</b><br><small>Professor(a) regente: ${c.teacher} · ${data.groups.filter(g=>g.classId===c.id).flatMap(g=>g.students).length} alunos</small></div><button class="action" data-action="edit-class" data-id="${c.id}">Editar turma</button></div>`).join('')}</section>`;if(state.page==='class-editor'){const c=getClass(state.classId);return `${header(c?`Editar ${c.name}`:'Criar turma')}${notice()}<form id="class-form" class="form" data-id="${c?c.id:''}"><div class="form-grid"><div class="field"><label>Nome da turma</label><input name="name" value="${c?c.name:''}" placeholder="Ex.: 4º ano A" required></div><div class="field"><label>Professor(a) regente</label><select name="teacher">${['Mariana Costa','João Pereira'].map(t=>`<option ${c&&c.teacher===t?'selected':''}>${t}</option>`).join('')}</select></div></div><p class="muted">A troca do professor regente não exclui grupos nem histórico pedagógico.</p><div class="form-actions"><button type="button" class="secondary" data-page="turmas">Cancelar</button><button class="save">Salvar turma</button></div></form>`}return `${header(state.page==='acompanhamento'?'Acompanhamento das turmas':'Visão da direção')}${notice()}<section class="panel"><h2>Relatórios recentes</h2>${data.reports.slice().sort((a,b)=>b.id-a.id).map(r=>`<div class="row"><div><b>${r.month} · ${getGroup(r.group).name}</b><br><small>${getClass(getGroup(r.group).classId).name} · foco: ${r.focus}</small></div><button class="action" data-action="view-report" data-id="${r.id}">Consultar</button></div>`).join('')}</section>`}
function loginView(){return `<section class="login"><div class="login-card"><div class="login-art"><div class="brand"><span class="brand-mark">✦</span> Trilhas Socioemocionais</div><div><h1>Educar também é acolher.</h1><p>Acompanhamento pedagógico socioemocional com planejamento mensal.</p></div></div><div class="login-form"><h2>Bem-vinda(o)!</h2><p>Escolha o perfil para explorar a demonstração.</p><div class="role-choice"><button class="role-btn active" data-role="Professor(a)">👩‍🏫 Professor(a)</button><button class="role-btn" data-role="Direção escolar">🏫 Direção escolar</button></div><button class="primary" data-action="enter">Acessar plataforma</button></div></div></section>`}
function main(){if(!state.role)return loginView();let content;if(state.role==='Direção escolar')content=directionView();else if(state.page==='inicio')content=teacherHome();else if(state.page==='grupos')content=groupsView();else if(state.page==='group-editor')content=groupsView(state.group);else if(state.page==='formulario')content=reportForm(state.group,state.editing?data.reports.find(r=>r.id===state.report):null);else if(state.page==='formularios')content=reportsView();else if(state.page==='report-detail')content=reportDetail(state.report);else if(state.page==='alunos')content=studentsView();else if(state.page==='historico')content=studentHistory(state.student);else if(state.page==='student-report')content=studentReport(state.student);else if(state.page==='planejamentos')content=plansView();else content=teacherHome();return `<div class="shell">${nav()}<main class="content">${content}</main></div>`}
function render(){app.innerHTML=main()}
document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.role){document.querySelectorAll('[data-role]').forEach(b=>b.classList.remove('active'));t.classList.add('active');return}if(t.dataset.page){state.page=t.dataset.page;state.editing=false;render();return}const a=t.dataset.action;if(a==='enter'){state.role=document.querySelector('[data-role].active').dataset.role;state.page='inicio';render()}if(a==='logout'){state.role='';render()}if(a==='answer'){state.group=t.dataset.id;state.editing=false;state.page='formulario';render()}if(a==='edit-members'){state.group=t.dataset.id;state.page='group-editor';render()}if(a==='open-plan'){state.group=t.dataset.id;state.page='planejamentos';render()}if(a==='view-report'){state.report=Number(t.dataset.id);state.page='report-detail';render()}if(a==='edit-report'){state.report=Number(t.dataset.id);state.group=data.reports.find(r=>r.id===state.report).group;state.editing=true;state.page='formulario';render()}if(a==='history'){state.student=t.dataset.id;state.page='historico';render()}if(a==='generate-student'){state.student=t.dataset.id;state.page='student-report';render()}if(a==='copy-report'){navigator.clipboard?.writeText(document.querySelector('#student-report-text').value);t.textContent='Relatório copiado ✓'}if(a==='new-class'){state.classId='';state.page='class-editor';render()}if(a==='edit-class'){state.classId=t.dataset.id;state.page='class-editor';render()}if(a==='save-members'){getGroup(t.dataset.id).students=[...document.querySelectorAll('input[name="member"]:checked')].map(i=>i.value);state.page='grupos';render()}});
document.addEventListener('submit',e=>{if(e.target.id==='report-form'){e.preventDefault();const f=new FormData(e.target),group=e.target.dataset.group,id=e.target.dataset.report,r=id?data.reports.find(x=>x.id===Number(id)):{id:Date.now(),month:'Setembro de 2026',sent:'07/09/2026',group,focus:'',answers:{},note:'',observations:{}};r.answers=Object.fromEntries(areas.map(a=>[a,f.get(a)]));r.focus=areas.find(a=>low.has(r.answers[a]))||'Acompanhamento contínuo';r.note=f.get('note');getGroup(group).students.forEach(s=>r.observations[s]=f.get(`student-${s}`)||'');if(!id)data.reports.push(r);state.group=group;state.page='planejamentos';state.editing=false;render()}if(e.target.id==='free-note'){e.preventDefault();const f=new FormData(e.target),name=e.target.dataset.student;(data.freeNotes[name]??=[]).push({date:f.get('date'),frequency:f.get('frequency'),text:f.get('text')});state.student=name;state.page='historico';render()}if(e.target.id==='class-form'){e.preventDefault();const f=new FormData(e.target),id=e.target.dataset.id;if(id)Object.assign(getClass(id),{name:f.get('name'),teacher:f.get('teacher')});else data.classes.push({id:`class-${Date.now()}`,name:f.get('name'),teacher:f.get('teacher')});state.page='turmas';render()}});
render();

