const D={groups:[['Azul',['Ana Clara Souza','Bernardo Lima','Cecília Martins']],['Amarelo',['Davi Oliveira','Elisa Rocha']],['Verde',['Felipe Alves','Gabriela Nunes']],['Vermelho',['Heitor Santos','Isabela Moraes']]],reports:[['Agosto 2026','Azul','Autorregulação emocional','Às vezes'],['Julho 2026','Amarelo','Empatia e cooperação','Raramente'],['Junho 2026','Verde','Convivência e respeito','Às vezes']]};let role='',page='inicio',g=0;const $=x=>document.querySelector(x), colors=['#5ba7dd','#efbd3e','#61b986','#e57c74'];
function login(){return '<section class="login"><div class="login-card"><div class="login-art"><div class="brand"><span class="brand-mark">✦</span> Trilhas Socioemocionais</div><h1>Educar também é acolher.</h1></div><div class="login-form"><h2>Bem-vinda(o)!</h2><p>Selecione o perfil para a apresentação.</p><div class="role-choice"><button class="role-btn active" data-r="Professor(a)">👩‍🏫 Professor(a)</button><button class="role-btn" data-r="Direção escolar">🏫 Direção escolar</button></div><button id="enter" class="primary">Acessar plataforma</button></div></div></section>'}
function pageHeader(t){return '<header class="topbar"><div><p class="eyebrow">'+role+'</p><h1>'+t+'</h1></div><div class="avatar">'+(role[0]||'T')+'</div></header>'}function note(){return '<div class="notice">🔒 Dados pedagógicos confidenciais. Registre situações e avanços, evitando rótulos permanentes.</div>'}
function nav(){let a=role==='Direção escolar'?['Início','Turmas','Acompanhamento']:['Início','Grupos','Alunos','Formulários','Planejamentos'];return '<aside class="side"><div class="brand"><span class="brand-mark">✦</span> Trilhas</div><nav class="nav">'+a.map(x=>'<button data-p="'+x.toLowerCase()+'" class="'+(page===x.toLowerCase()?'active':'')+'">'+x+'</button>').join('')+'</nav></aside>'}
function plan(i){let x=D.groups[i],r=D.reports.find(z=>z[1]===x[0])||['Setembro','', 'Autonomia e participação','Às vezes'];return '<div class="recommendation"><h3>'+x[0]+' · '+r[2]+'</h3><p><b>BNCC:</b> Competências gerais 8 e 9.</p><p><b>Intenção:</b> desenvolver reconhecimento de emoções, empatia e cooperação.</p><p><b>Atividade:</b> cartões de emoções e dinâmica cooperativa.</p><p>📚 <b>O Monstro das Cores</b> · Roda: “Como posso me acalmar?”</p><button class="action" data-plan="'+i+'">Planejamento completo →</button></div>'}
function home(){return pageHeader('Visão geral')+note()+'<div class="cards"><div class="metric"><b>9</b><span>Alunos</span></div><div class="metric"><b>4</b><span>Grupos</span></div><div class="metric"><b>3</b><span>Relatórios</span></div></div><h2 style="margin-top:20px">Planejamentos mensais</h2>'+D.groups.map((x,i)=>'<section class="panel" style="margin:12px 0;border-left:8px solid '+colors[i]+'">'+plan(i)+'</section>').join('')}
function groups(){return pageHeader('Grupos')+note()+'<div class="rows">'+D.groups.map((x,i)=>'<section class="panel group-row" style="border-left:9px solid '+colors[i]+'"><div><h2>Grupo '+x[0]+'</h2><p class="muted">'+x[1].join(' · ')+'</p></div><div><button class="secondary" data-g="'+i+'">Responder formulário</button><button class="action" data-edit="'+i+'">Editar integrantes</button></div></section>').join('')+'</div>'}
function form(){let x=D.groups[g];return pageHeader('Formulário mensal · Grupo '+x[0])+note()+'<form class="form" id="form"><div class="report-info"><div><span>Período automático</span><b>01 a 30 de setembro de 2026</b></div><div><span>Turma</span><b>2º ano A</b></div></div>'+['Autoconhecimento e autocuidado','Autorregulação emocional','Empatia e cooperação','Convivência e respeito','Autonomia e participação'].map(q=>'<div class="question"><label>'+q+'</label><select><option>Ainda não observado</option><option>Raramente</option><option>Às vezes</option><option>Frequentemente</option><option>Sempre</option></select></div>').join('')+'<div class="field full"><label>Observação geral do grupo</label><textarea></textarea></div><h2>Observações individuais</h2>'+x[1].map(n=>'<div class="field"><label>'+n+'</label><textarea placeholder="Observação opcional"></textarea></div>').join('')+'<div class="form-actions"><button type="button" class="secondary">Salvar rascunho</button><button class="save">Enviar relatório</button></div></form>'}
function reports(){return pageHeader('Formulários respondidos')+note()+'<section class="panel"><h2>Histórico mensal</h2>'+D.reports.map((r,i)=>'<div class="row"><div><b>'+r[0]+' · Grupo '+r[1]+'</b><br><small>Foco: '+r[2]+' · resposta: '+r[3]+'</small></div><button class="action" data-plan="'+i+'">Ver / Editar</button></div>').join('')+'</section>'}
function direction(){return pageHeader(page==='turmas'?'Turmas':'Acompanhamento das turmas')+note()+'<section class="panel"><h2>'+ (page==='turmas'?'Turmas e professores regentes':'Andamento pedagógico')+'</h2><p>2º ano A · Mariana Costa · 2 grupos · 5 alunos</p><p>3º ano B · João Pereira · 2 grupos · 4 alunos</p><button class="secondary">Editar organização</button></section>'}
function render(){if(!role){$('#app').innerHTML=login()}else{let b=role==='Direção escolar'?direction():page==='inicio'?home():page==='grupos'?groups():page==='formulários'?reports():page==='formulario'?form():page==='planejamentos'?pageHeader('Planejamento completo')+plan(g):page==='alunos'?pageHeader('Histórico dos alunos')+'<section class="panel"><h2>Ana Clara Souza</h2><p>Avanço em participação; manter atividades de autorregulação.</p><button class="secondary">Gerar relatório do aluno</button></section>':home();$('#app').innerHTML='<div class="shell">'+nav()+'<main class="content">'+b+'</main></div>'}bind()}function bind(){document.querySelectorAll('[data-r]').forEach(x=>x.onclick=()=>{document.querySelectorAll('[data-r]').forEach(y=>y.classList.remove('active'));x.classList.add('active')});let e=$('#enter');if(e)e.onclick=()=>{role=$('.active[data-r]').dataset.r;render()};document.querySelectorAll('[data-p]').forEach(x=>x.onclick=()=>{page=x.dataset.p;render()});document.querySelectorAll('[data-g]').forEach(x=>x.onclick=()=>{g=+x.dataset.g;page='formulario';render()});document.querySelectorAll('[data-plan]').forEach(x=>x.onclick=()=>{g=+x.dataset.plan;page='planejamentos';render()});let f=$('#form');if(f)f.onsubmit=e=>{e.preventDefault();page='planejamentos';render()}}render();


