const groups=[['Azul','Ana, Bernardo e Cecília','#57a8dd'],['Amarelo','Davi e Elisa','#efbf3e'],['Verde','Felipe e Gabriela','#62b982'],['Vermelho','Heitor e Isabela','#e47b73']];
let page='inicio',selected=0;
const $=s=>document.querySelector(s);
function shell(body){return '<div class="shell"><aside class="side"><div class="brand"><span class="brand-mark">✦</span> Trilhas</div><nav class="nav">'+['Início','Grupos','Alunos','Formulários','Planejamentos'].map(x=>'<button data-p="'+x.toLowerCase()+'" class="'+(page===x.toLowerCase()?'active':'')+'">'+x+'</button>').join('')+'</nav></aside><main class="content">'+body+'</main></div>'}
function h(t){return '<header class="topbar"><div><p class="eyebrow">Trilhas Socioemocionais</p><h1>'+t+'</h1></div><div class="avatar">MC</div></header>'}function notice(){return '<div class="notice">🔒 Registros pedagógicos confidenciais. Use observações contextualizadas e acolhedoras.</div>'}
function plan(i){let g=groups[i];return '<div class="recommendation"><h3>Planejamento do Grupo '+g[0]+'</h3><p><b>BNCC:</b> competências 8 e 9 · Autoconhecimento, empatia e cooperação.</p><p>Atividade: cartões de emoções e roda de conversa. 📚 Leitura: <b>O Monstro das Cores</b>.</p><button class="action" data-plan="'+i+'">Ver planejamento completo →</button></div>'}
function home(){return h('Olá, Mariana!')+notice()+'<div class="cards"><div class="metric"><b>9</b><span>Alunos</span></div><div class="metric"><b>4</b><span>Grupos</span></div><div class="metric"><b>2</b><span>Formulários</span></div></div><h2 style="margin-top:24px">Grupos e planejamentos recomendados</h2>'+groups.slice(0,2).map((g,i)=>'<section class="panel" style="margin:14px 0;border-left:8px solid '+g[2]+'"><h2>Grupo '+g[0]+'</h2>'+plan(i)+'</section>').join('')}
function groupsPage(){return h('Grupos')+notice()+groups.map((g,i)=>'<section class="panel group-row" style="margin:13px 0;border-left:9px solid '+g[2]+'"><div><h2>Grupo '+g[0]+'</h2><p class="muted">2º ano A · '+g[1]+'</p></div><button class="secondary" data-form="'+i+'">Responder formulário</button></section>').join('')}
function form(){let g=groups[selected];return h('Formulário mensal · Grupo '+g[0])+notice()+'<form class="form" id="f"><div class="report-info"><div><span>Período automático</span><b>01 a 30 de setembro de 2026</b></div><div><span>Turma</span><b>2º ano A</b></div></div>'+['Autoconhecimento','Autorregulação emocional','Empatia e cooperação','Convivência e respeito','Autonomia e participação'].map(x=>'<div class="question"><label>'+x+': o grupo apresenta avanços?</label><select><option>Ainda não observado</option><option>Raramente</option><option selected>Às vezes</option><option>Frequentemente</option><option>Sempre</option></select></div>').join('')+'<div class="field full"><label>Observações individuais</label><textarea placeholder="Escreva observações específicas dos alunos, se necessário."></textarea></div><div class="form-actions"><button class="save">Enviar e gerar planejamento</button></div></form>'}
function planning(){return h('Planejamento recomendado')+notice()+plan(selected)+'<section class="panel"><h2>Próximos passos</h2><p>Dinâmica cooperativa, roda de conversa orientada e projeto “Mural das Emoções”. Registre a participação no próximo relatório.</p></section>'}
function students(){return h('Alunos')+notice()+'<section class="panel"><h2>Histórico do aluno</h2><p>Relatórios mensais, observações e acompanhamento pedagógico.</p><button class="secondary" id="report">Gerar relatório do aluno</button></section>'}
function report(){return h('Relatório do aluno')+'<section class="panel"><h2>Ana Clara Souza · 2º ano A</h2><p>Síntese dos questionários e observações: apresenta participação crescente nas atividades, com necessidade de continuar praticando estratégias de autorregulação.</p><p>Sugestão: manter rodas de conversa e propostas cooperativas.</p><button class="secondary" id="copy">Copiar relatório</button></section>'}
function forms(){return h('Formulários respondidos')+notice()+'<section class="panel"><h2>Setembro de 2026</h2><p>Grupo Azul · 2º ano A · Professora Mariana Costa</p><button class="action" data-plan="0">Ver formulário respondido</button></section>'}
function render(){let b=page==='inicio'?home():page==='grupos'?groupsPage():page==='formulario'?form():page==='planejamentos'?planning():page==='alunos'?students():page==='relatorio'?report():forms();$('#app').innerHTML=shell(b);document.querySelectorAll('[data-p]').forEach(x=>x.onclick=()=>{page=x.dataset.p;render()});document.querySelectorAll('[data-form]').forEach(x=>x.onclick=()=>{selected=+x.dataset.form;page='formulario';render()});document.querySelectorAll('[data-plan]').forEach(x=>x.onclick=()=>{selected=+x.dataset.plan;page='planejamentos';render()});let f=$('#f');if(f)f.onsubmit=e=>{e.preventDefault();page='planejamentos';render()};let r=$('#report');if(r)r.onclick=()=>{page='relatorio';render()};let c=$('#copy');if(c)c.onclick=()=>navigator.clipboard.writeText($('.panel').innerText)}render();

